version: "3.7"
services:
  kratos-migrate:
    image: oryd/kratos:v1.0.0
    environment:
      - DSN=postgres://ory:secret@postgresd:5432/ory?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.0.0
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://ory:secret@postgresd:5432/ory?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet
  postgresd:
    image: postgres:11.8
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ory
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ory
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - intranet
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - intranet
  ory-ui-nextjs:
    build:
      context: ./ory-ui-nextjs
    volumes:
      - ./ory-ui-nextjs:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NEXT_PUBLIC_KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - NEXT_PUBLIC_KRATOS_PUBLIC_URL=http://kratos:4433/
    ports:
      - "3000:3000"
    networks:
      - intranet
    restart: on-failure
  # hydra:
  #   image: oryd/hydra:v2.2.0
  #   ports:
  #     - "4444:4444" # Public port
  #     - "4445:4445" # Admin port
  #     - "5555:5555" # Port for hydra token user
  #   command: serve -c /etc/config/hydra/hydra.yml all --dev
  #   volumes:
  #     - type: bind
  #       source: ./hydra
  #       target: /etc/config/hydra
  #   environment:
  #     - DSN=postgres://ory:secret@postgresd:5432/ory?sslmode=disable&max_conns=20&max_idle_conns=4
  #   restart: unless-stopped
  #   depends_on:
  #     - hydra-migrate
  #   networks:
  #     - intranet

  # hydra-migrate:
  #   image: oryd/hydra:v2.2.0
  #   environment:
  #     - DSN=postgres://ory:secret@postgresd:5432/ory?sslmode=disable&max_conns=20&max_idle_conns=4
  #   command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
  #   volumes:
  #     - type: bind
  #       source: ./hydra
  #       target: /etc/config/hydra
  #   restart: on-failure
  #   networks:
  #     - intranet

  # consent:
  #   environment:
  #     - HYDRA_ADMIN_URL=http://hydra:4445
  #   image: oryd/hydra-login-consent-node:v2.2.0
  #   ports:
  #     - "3100:3000"
  #   restart: unless-stopped
  #   networks:
  #     - intranet
networks:
  intranet:
volumes:
  postgres-data:
